import {defaultGroups,defaultSite} from './defaults';

const project=(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'');
const key=import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const sessionKey='dunavska-kitka-admin-session';
type Session={access_token:string;refresh_token:string;expires_at:number};
let pendingRefresh:Promise<Session|null>|null=null;
function configured(){if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(project)||!key)throw Error('Връзката с базата данни още не е настроена.');}
function saved():Session|null{try{return JSON.parse(sessionStorage.getItem(sessionKey)||'null')}catch{return null}}
function store(s:any):Session{const session={access_token:s.access_token,refresh_token:s.refresh_token,expires_at:Math.floor(Date.now()/1000)+(s.expires_in||3600)};sessionStorage.setItem(sessionKey,JSON.stringify(session));return session}
export async function signOut(){const s=saved();sessionStorage.removeItem(sessionKey);if(s)await fetch(project+'/auth/v1/logout',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+s.access_token}}).catch(()=>{})}
async function session():Promise<Session|null>{const s=saved();if(!s)return null;if(s.expires_at>Date.now()/1000+45)return s;
 if(!pendingRefresh)pendingRefresh=(async()=>{try{const r=await fetch(project+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)throw Error('refresh');return store(await r.json())}catch{sessionStorage.removeItem(sessionKey);return null}finally{pendingRefresh=null}})();return pendingRefresh}
async function request(path:string,options:RequestInit={},auth=false):Promise<any>{configured();const s=await session();if(auth&&!s)throw Error('Влезте като администратор.');const r=await fetch(project+path,{...options,headers:{apikey:key,...(s?{Authorization:'Bearer '+s.access_token}:{}),...options.headers}});if(!r.ok){const error=await r.json().catch(()=>({}));throw Error(error.message||error.error_description||error.error||`Заявката не успя (${r.status}).`)}if(r.status===204||r.headers.get('content-length')==='0')return null;const text=await r.text();return text?JSON.parse(text):null}
export async function signIn(email:string,password:string){configured();const r=await fetch(project+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const result=await r.json();if(!r.ok)throw Error(result.error_description||result.msg||'Невалиден имейл или парола.');store(result);try{if(!await isAdmin())throw Error('Този профил няма администраторски достъп.')}catch(e){await signOut();throw e}}
export async function isAdmin(){if(!await session())return false;return request('/rest/v1/rpc/is_club_admin',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},true) as Promise<boolean>}
async function rows(kind:string){const filter=kind==='registration'?'&kind=eq.registration':'';return request('/rest/v1/site_records?select=id,kind,data,created&order=created.desc'+filter,{headers:{Accept:'application/json'}}) as Promise<any[]>}
export async function loadData(){const admin=await isAdmin();const records=await rows('');const list=(kind:string)=>records.filter(r=>r.kind===kind).map(r=>({...r.data,id:r.id,created:r.created}));const groups=list('group');const polls=list('poll');const out:any={groups:[...defaultGroups.filter(g=>!groups.some((r:any)=>r.id===g.id)),...groups].filter((g:any)=>!g.hidden),lessons:list('lesson'),notices:list('notice'),polls:admin?polls:polls.filter((p:any)=>p.active),club:list('club')[0]||null,site:{...defaultSite,...(list('site')[0]||{})},pages:list('page'),isAdmin:admin};if(admin){out.registrations=list('registration');const votes=await request('/rest/v1/votes?select=poll_id,answer',{headers:{Accept:'application/json'}},true);const tally=new Map<string,any>();for(const v of votes){const k=v.poll_id+':'+v.answer;const row=tally.get(k)||{poll_id:v.poll_id,answer:v.answer,count:0};row.count++;tally.set(k,row)}out.results=[...tally.values()]}return out}
const allowed=new Set(['notice','lesson','poll','group','club','registration','site','page']);
export async function act(b:any){if(b.action==='register'){await request('/rest/v1/rpc/register_dancer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_name:b.data.name,p_email:b.data.email,p_phone:b.data.phone,p_group_id:b.data.group,p_note:b.data.note||'',p_consent:b.data.consent})});return {ok:true}}
 if(b.action==='vote'){await request('/rest/v1/rpc/submit_vote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_poll_id:b.id,p_answer:b.answer,p_voter:b.voter})});return {ok:true}}
 if(!await isAdmin())throw Error('Нямате администраторски достъп.');if(!allowed.has(b.kind))throw Error('Непознат вид съдържание.');
 if(b.action==='delete'){if(b.kind==='group'&&defaultGroups.some(g=>g.id===b.id))return act({action:'save',kind:'group',id:b.id,data:{...defaultGroups.find(g=>g.id===b.id),hidden:true}});await request('/rest/v1/site_records?id=eq.'+encodeURIComponent(b.id)+'&kind=eq.'+b.kind,{method:'DELETE'},true);return {ok:true}}
 if(b.action!=='save'||!b.data||JSON.stringify(b.data).length>15000)throw Error('Невалидни данни.');if(b.kind==='lesson'&&!/^https:\/\//.test(b.data.url||''))throw Error('Използвайте HTTPS видео адрес.');const id=b.kind==='club'?'club':b.kind==='site'?'site':b.id||crypto.randomUUID();await request('/rest/v1/site_records?on_conflict=id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id,kind:b.kind,data:b.data})},true);return {ok:true,id}}
export async function upload(file:File){if(!await isAdmin())throw Error('Нямате администраторски достъп.');const image=['image/jpeg','image/png','image/webp'].includes(file.type);const video=['video/mp4','video/webm','video/quicktime'].includes(file.type);if((!image&&!video)||file.size>50*1024*1024)throw Error('Изберете снимка или видео до 50 MB.');const name=crypto.randomUUID()+'.'+(image?file.type.split('/')[1]:file.type.split('/')[1]);configured();const s=await session();const r=await fetch(project+'/storage/v1/object/club-media/'+name,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+s!.access_token,'Content-Type':file.type,'Cache-Control':'3600'},body:file});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.message||'Качването не успя.')}return project+'/storage/v1/object/public/club-media/'+name}

export async function signUp(email:string,password:string){configured();const r=await fetch(project+'/auth/v1/signup',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||d.message||'Регистрацията не успя.');return d}
export async function grantAdmin(email:string){if(!await isAdmin())throw Error('Нямате достъп.');await request('/rest/v1/rpc/grant_club_admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_email:email})},true)}
