import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const database=new DatabaseSync(':memory:');database.exec(readFileSync('drizzle/0002_cardless.sql','utf8'));
const route=readFileSync('app/api/auth/[action]/route.ts','utf8');
const query=prefix=>{const s=route.split("prepare('").map(x=>x.split("')")[0]).find(x=>x.startsWith(prefix));assert(s);return database.prepare(s)};
const setup=query('INSERT INTO admin_users(email,password_hash) SELECT');assert.equal(setup.all('owner@example.com','hash1').length,1);assert.equal(setup.all('attacker@example.com','hash2').length,0);
const rate=query('INSERT INTO admin_login_limits');for(let i=1;i<=11;i++)assert.equal(rate.all('ip',1)[0].attempts,i);assert.equal(rate.all('ip',2)[0].attempts,1);
database.prepare('INSERT INTO admin_sessions VALUES(?,?,?,?)').run('tokenhash','owner@example.com','hash1',100);
const auth=readFileSync('lib/access-auth.ts','utf8').split("prepare('")[1].split("')")[0];const session=database.prepare(auth);assert.equal(session.get('tokenhash',50).email,'owner@example.com');assert.equal(session.get('forged',50),undefined);assert.equal(session.get('tokenhash',100),undefined);database.prepare('UPDATE admin_users SET password_hash=?').run('hash2');assert.equal(session.get('tokenhash',50),undefined);
const bytes=Buffer.alloc(5*1024*1024,121);database.prepare('INSERT INTO media_files VALUES(?,?,?)').run('image','image/png',bytes.length);const chunk=database.prepare('INSERT INTO media_chunks VALUES(?,?,?)');for(let i=0,n=0;i<bytes.length;i+=196608,n++)chunk.run('image',n,bytes.subarray(i,i+196608).toString('base64'));const restored=Buffer.concat(database.prepare('SELECT data FROM media_chunks WHERE file_id=? ORDER BY part').all('image').map(row=>Buffer.from(row.data,'base64')));assert.deepEqual(bytes,restored);console.log('Atomic bootstrap, rate-limit windows, expired/forged/revoked sessions and 5 MB media roundtrip passed');
