CREATE TABLE IF NOT EXISTS admin_users (email TEXT PRIMARY KEY NOT NULL,password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_sessions (token_hash TEXT PRIMARY KEY NOT NULL,email TEXT NOT NULL,password_hash TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS admin_sessions_expiry ON admin_sessions(expires);
CREATE TABLE IF NOT EXISTS admin_login_limits (key TEXT PRIMARY KEY NOT NULL,window INTEGER NOT NULL,attempts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS media_files (id TEXT PRIMARY KEY NOT NULL,content_type TEXT NOT NULL,size INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS media_chunks (file_id TEXT NOT NULL,part INTEGER NOT NULL,data TEXT NOT NULL,PRIMARY KEY(file_id,part));
