'use client';
import {useState} from 'react';
import {defaultSite} from '@/lib/defaults';
import {Plus,Trash2} from 'lucide-react';
const fields=[
 ['topNote','Текст в горната лента','text'],['joinButton','Бутон за записване','text'],['heroEyebrow','Кратък надпис на началната','text'],['heroButton','Основен бутон на началната','text'],['heroNote','Бележка под бутоните','textarea'],
 ['heroTitle','Начално заглавие','textarea'],['heroText','Увод на началната страница','textarea'],['heroImage','Основна снимка','image'],
 ['homeGroupsTitle','Заглавие над групите','text'],['homeGroupsIntro','Текст над групите','textarea'],['homeNoticesTitle','Заглавие на обявите','text'],['homeCardTitle','Заглавие на зелената карта','text'],['homeCardText','Текст на зелената карта','textarea'],
 ['aboutTitle','Заглавие „За клуба“','text'],['aboutSubtitle','Подзаглавие „За клуба“','text'],['aboutEyebrow','Надпис „За клуба“','text'],['aboutImage','Снимка на ръководителя','image'],
 ['groupsTitle','Заглавие на групите','text'],['lessonsTitle','Заглавие на уроците','text'],['lessonsIntro','Въведение към уроците','text'],
 ['rehearsalsTitle','Заглавие на репетициите','text'],['scheduleImage','Снимка на графика','image'],
 ['pollsTitle','Заглавие на анкетите','text'],['joinTitle','Заглавие на записването','text'],['joinIntro','Текст при записването','textarea'],['joinNote','Бележка при записването','text'],['footerText','Текст във футъра','text']
] as const;
export default function SiteEditor({site,pages,action,reload,uploadFile}:any){
 const [form,setForm]=useState<any>({...defaultSite,...site});const [draft,setDraft]=useState<any>({slug:'',title:'',body:'',image:''});const [uploading,setUploading]=useState('');const [notice,setNotice]=useState('');
 async function upload(file:File|undefined,field:string,onUrl:(u:string)=>void){if(!file)return;setUploading(field);setNotice('');try{const url=await uploadFile(file);onUrl(url);setNotice('Снимката е качена. Натиснете „Запази“ за публикуване.')}catch(e:any){setNotice(e.message)}finally{setUploading('')}}
 return <div className="site-editor">
 <div className="panel"><h2>Съдържание и снимки</h2><p>Променяйте текстовете и снимките на основните страници. Заглавието приема нов ред.</p><div className="site-fields">{fields.map(([key,label,type])=><label key={key}>{label}{type==='textarea'?<textarea value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/>:type==='image'?<><input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!uploading} onChange={e=>upload(e.target.files?.[0],key,u=>setForm((f:any)=>({...f,[key]:u})))}/>{form[key]&&<img className="editor-image" src={form[key]} alt={'Текуща снимка: '+label}/>}</>:<input value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}</div><button className="button" disabled={!!uploading} onClick={async()=>{if(await action({action:'save',kind:'site',data:form}))setNotice('Промените са запазени.')}}>Запази промените</button></div>
 <div className="panel"><h2>Допълнителни страници</h2><p>Страниците се появяват в навигацията и могат да се променят или изтриват тук.</p><div className="admin-list">{pages.map((p:any)=><PageEditor key={p.id} page={p} action={action} upload={upload} uploading={uploading} onMessage={setNotice}/>)}</div><form className="form extra-page" onSubmit={async e=>{e.preventDefault();if(await action({action:'save',kind:'page',data:draft})){setDraft({slug:'',title:'',body:'',image:''});setNotice('Страницата е добавена.')}}}><h3>Нова страница</h3><label>Кратък адрес на латиница<input required pattern="[a-z][a-z0-9-]{1,39}" placeholder="naprimer-kontakti" value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})}/></label><label>Заглавие<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Текст<textarea value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><label>Снимка<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0],'new-page',u=>setDraft((d:any)=>({...d,image:u})))}/>{draft.image&&<img className="editor-image" src={draft.image} alt="Снимка за новата страница"/>}</label><button className="button" disabled={!!uploading}><Plus size={16}/>Добави страница</button></form></div>
 {notice&&<p role="status" className="edit-notice">{notice}</p>}
 </div>
}
function PageEditor({page,action,upload,uploading,onMessage}:any){const [draft,setDraft]=useState<any>(page);return <form className="form page-edit" onSubmit={async e=>{e.preventDefault();if(await action({action:'save',kind:'page',id:page.id,data:draft}))onMessage('Страницата е запазена.')}}><div className="row-between"><h3>{page.title}</h3><button type="button" className="danger" onClick={async()=>{if(confirm('Да изтрием ли страницата?'))await action({action:'delete',kind:'page',id:page.id})}}><Trash2 size={15}/> Изтрий</button></div><label>Адрес<input required pattern="[a-z][a-z0-9-]{1,39}" value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})}/></label><label>Заглавие<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Текст<textarea value={draft.body||''} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><label>Снимка<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!uploading} onChange={e=>upload(e.target.files?.[0],page.id,(u:string)=>setDraft((d:any)=>({...d,image:u})))}/>{draft.image&&<img className="editor-image" src={draft.image} alt={'Снимка на '+draft.title}/>}</label><button className="button" disabled={!!uploading}>Запази страницата</button></form>}
